name: cei_mobile
description: "MA CEI"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.5.3

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  http: ^1.3.0
  internet_connection_checker: ^3.0.1
  go_router: ^15.1.0
  skeletonizer: ^1.4.3
  nb_utils: ^7.1.4
  provider: ^6.1.4
  shared_preferences: ^2.5.3
  google_fonts: ^6.2.1
  flutter_carousel_widget: ^3.1.0
  image_picker: ^1.1.2
  file_picker: ^10.1.2
  dotted_border: ^2.1.0
  flutter_map: ^8.1.1
  fluentui_system_icons: ^1.1.273
  google_maps_flutter: ^2.12.1
  freezed_annotation: ^2.4.4
  mobx: ^2.5.0
  flutter_mobx: ^2.3.0
  flutter_launcher_icons: ^0.14.3
  qr_flutter: ^4.1.0
  open_filex: ^4.3.1
  cached_network_image: ^3.3.0
  path_provider: ^2.1.1
  file_icon: ^1.0.0
  intl_phone_number_input: ^0.7.4
  dropdown_search: ^6.0.2
  wolt_modal_sheet: ^0.11.0
  share_plus: ^11.0.0
  lottie: ^2.3.2
  timeline_tile: ^2.0.0
  face_camera: ^0.1.4
  image: ^4.3.0
  flutter_document_reader_api: 7.5.1093
  flutter_document_reader_core_fullauthrfid: 7.5.887
  flutter_face_api: ^6.4.875
  flutter_face_core_match: ^6.4.243
  signature: ^6.0.0
  percent_indicator: ^4.2.5
  fl_chart: ^1.0.0
  intl_phone_field: ^3.2.0
  flex_color_picker: ^3.7.1
  pdf: ^3.11.3
  permission_handler: ^12.0.0+1
  flutter_file_downloader: ^2.1.0
  url_launcher: ^6.3.1
  flutter_expandable_fab: ^2.5.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^4.0.0
  build_runner: ^2.4.15
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  mobx_codegen: ^2.6.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/animations/
    - assets/licences/
    - assets/data/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins/Poppins-Thin.ttf
        - asset: fonts/Poppins/Poppins-ThinItalic.ttf
          weight: 100
        - asset: fonts/Poppins/Poppins-Light.ttf
        - asset: fonts/Poppins/Poppins-LightItalic.ttf
          weight: 300
        - asset: fonts/Poppins/Poppins-Regular.ttf
        - asset: fonts/Poppins/Poppins-Italic.ttf
          weight: 400
        - asset: fonts/Poppins/Poppins-Medium.ttf
        - asset: fonts/Poppins/Poppins-MediumItalic.ttf
          weight: 500
        - asset: fonts/Poppins/Poppins-Bold.ttf
        - asset: fonts/Poppins/Poppins-BoldItalic.ttf
          weight: 700
        - asset: fonts/Poppins/Poppins-Black.ttf
        - asset: fonts/Poppins/Poppins-BlackItalic.ttf
          weight: 900
    - family: Roboto
      fonts:
        - asset: fonts/Roboto/Roboto-Regular.ttf
          weight: 400
        - asset: fonts/Roboto/Roboto-Medium.ttf
          weight: 500
        - asset: fonts/Roboto/Roboto-Bold.ttf
          weight: 700
        - asset: fonts/Roboto/Roboto-Black.ttf
          weight: 900
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  remove_alpha_ios: true
  min_sdk_android: 21
  image_path: 'assets/images/icon.png'
  adaptive_icon_background: '#FFFFFF'
  adaptive_icon_foreground: 'assets/images/icon.png'
